### ISSUE TITLE
Custom Build Test

### ISSUE THREAD

**Issue by YT-Advanced** [wjz304/MagiskOnWSABuild#13]

**Comment by YT-Advanced** [comment]
Hi @wjz304 
Here is an example of the problem I mentioned in pull request #14. And can I use your workflow for my repos WSA-Script and how about if you become a member of my repos. Thanks !

**Comment by wjz304** [comment]
> Hi @wjz304 Here is an example of the problem I mentioned in pull request #14. And can I use your workflow for my repos WSA-Script and how about if you become a member of my repos. Thanks !

No problem, you can!
