### ISSUE TITLE
Custom

### ISSUE THREAD

**Issue by aicynide** [wjz304/MagiskOnWSABuild#15]
--arch x64 --release-type retail --magisk-ver stable --gapps-brand OpenGApps --gapps-variant pico --root-sol magisk --compress-format zip --remove-amazon

**Comment by aicynide** [comment]
transfer

**Comment by aicynide** [comment]
transfer

**Comment by aicynide** [comment]
transfer

**Comment by wjz304** [comment]
太长时间没人用，系统关掉了周期性的任务

**Comment by wjz304** [comment]
transfer
