### ISSUE TITLE
Custom

### ISSUE THREAD

**Issue by 1900forever** [wjz304/MagiskOnWSABuild#6]
--arch x64 --release-type WIF --magisk-ver release --gapps-brand OpenGApps --gapps-variant pico --root-sol magisk --compress-format 7z --remove-amazon --offline

**Comment by wjz304** [comment]
It seems that ‘--magisk-custom’ needs to put a magisk.apk, i need to confirm.

**Comment by 1900forever** [comment]
delete builds
